<a href="https://colab.research.google.com/github/manaswithak/python/blob/main/manaswitha_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np  #creating alias for numpy as np for easy use

a=np.array([1,2,3,4])  #creating numpy array
b=np.array([[1,2,3,4],["abc",True,5.3,3]])  #this is format for 2d array(two arrays in list) ->one matrix
print(b)
print(b.shape)
print(b.ndim)
print(a)
print(a.ndim) #ndim->number of dimension
print(a.shape) #shape=rows*columns
print(a.dtype)  #U23 if string and mixed datatype then U32, int 64 is if only int
c=np.array([[[1,2],[2,4]],[[1,2],[3,4]]]) #two matrix -> three dimensional matrix
print(c)
print(c.ndim)
print(c.shape)

d=np.zeros([1,3])  #it creates 1 row 3 columns with 0 as values in it
print(d)
e=np.zeros([3,5])
print(e)

f=np.ones([3,5])  #creates array of ones with 3 rows and 5 columns
print(f)

g=np.eye(5)  #creates diagonal of 1 and remaining 0 with 5 row 5 column
print(g)
g=np.eye(3)
print(g)

h=np.arange(1,10,1) #arange->(start,stop,step) print elements from 1 to 9 linearly here 10 will not be there as it is stop
print(h)
h=np.arange(1,10,2)  #this will print 1 then go to 3 as step is 2 which is jump
print(h)
h=np.arange(3,50,3)
print(h)

i=np.linspace(0,1,5) #linspace->(start,stop,countofsplit) #between 0 and 1 it will split to 5 that is countofsplit
print(i)
i=np.linspace(0,10,5)  #it will include stop value also in this
print(i)
i=np.linspace(0,100,5)
print(i)

#indexing and slicing
#                0       1
arr=np.array([[1,2,3],[4,5,6]])  #for indexing it starts from 0 row 1 row and inside elements 0,1,2....
#              0 1 2   0 1 2
print(arr)
print(arr.shape)
print(arr[1,1])
print(arr[0,2])
print(arr[:,2])  #slicing : here all rows are comsidered at start and 3rd column of each row so from all rows 3rd column element is printed
print(arr[:,0])
print(arr[1,:])  #1st row with all columns
print(arr.shape)
print(arr.reshape(3,2))  #changing to 3 rows and 2 columns
print(arr.flatten()) #converts it is 1 dimension

#arithmetic and broadcasting
a=np.array([1,2,3])  #same dimension direct operation but if different dimension then we do broadcasting
b=np.array([10,20,30])
print(a+b)
print(a*3)
print(a-b)
c=np.array([[1],[2],[3]]) #3*1
d=np.array([10,20,30])  #1*3
print(c+d) #since c and d has different dimension so broadcasting is done
''' [1] + [10,20,30] =>(BROADCASTING)=> [10+1 20+1 30+1]
    [2] + [10,20,30]                    [10+2 20+2 30+2]
    [3] + [10,20,30]                    [10+3 20+3 30+3] '''

#aggregate functions
arr=np.array([[1,2],[3,4]])
print(arr.sum())   #adding of all elements in matrix
print(arr.mean())  #avg of all elements
print(arr.max(axis=0))  #here if 0 means row and 1 is column
print(np.median(arr))

#boolean indexing and filtering
a=np.array([1,2,3,4,5])
mask=a>3
print(a[mask])

[['1' '2' '3' '4']
 ['abc' 'True' '5.3' '3']]
(2, 4)
2
[1 2 3 4]
1
(4,)
int64
[[[1 2]
  [2 4]]

 [[1 2]
  [3 4]]]
3
(2, 2, 2)
[[0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]
[ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48]
[0.   0.25 0.5  0.75 1.  ]
[ 0.   2.5  5.   7.5 10. ]
[  0.  25.  50.  75. 100.]
[[1 2 3]
 [4 5 6]]
(2, 3)
5
3
[3 6]
[1 4]
[4 5 6]
(2, 3)
[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]
[11 22 33]
[3 6 9]
[ -9 -18 -27]
[[11 21 31]
 [12 22 32]
 [13 23 33]]
10
2.5
[3 4]
2.5
[4 5]
